#!/bin/bash

# Get the number of valid users
user_list=$(awk -F: '/\/bin\/bash|\/bin\/zsh|\/bin\/sh|\/bin\/dash/{print $1}' /etc/passwd | grep -v "$USER" | grep -v "root")

# if empty just launch as current user
if [ -z "$user_list" ]; then
	$1;
	exit 0;
fi

# adapt length of list depending on number of users
list_lenght=$(( 5+$(( $(echo -e $user_list | wc -w )*3 )) ))

# Let user select the user
user=$(awk -F: '/\/bin\/bash|\/bin\/zsh|\/bin\/sh|\/bin\/dash/{print $1}' /etc/passwd | grep -v "$USER" | grep -v "root" | tofi -c $HOME/.config/tofi/select --prompt-text="   " --height $list_lenght%)

# if no user just cancel
if [ $? -ne 0 ] || [ -z "$user" ]; then
	exit 1;
fi

# prompt for the password
pas=$(echo \"\" | tofi -c $HOME/.config/tofi/passwd)

# if canceled exit
if [ $? -ne 0 ]; then
	exit 1;
fi

# form the terminal passed as $1 start a session as the selected user
$1 script -q -c "expect -c 'spawn su - $user; expect \":\"; send \"$pas\r\"; expect \"$ \"; interact; '" /dev/null
